name: PR tests

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  test:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential tcl

    - name: Run tests
      run: make test
